export type GlossaryCategory = 'Recuperação' | 'Carga' | 'Treino' | 'Planejamento';

export type GlossaryEntry = {
  id: string;
  term: string;
  fullName: string;
  unit?: string;
  category: GlossaryCategory;
  summary: string;
  appUse: string;
  direction: string;
  baseline: string;
  source: 'Polar' | 'Intervals.icu' | 'Cálculo do app' | 'Percepção do atleta';
  limitations: string;
  related?: string[];
};

const personalBaseline = 'Seu padrão e a tendência de vários dias importam mais que um valor isolado.';
const sensorLimits = 'Pode variar com medição, rotina, álcool, estresse, doença e horário. Não é diagnóstico médico.';

export const glossary: GlossaryEntry[] = [
  { id: 'hrv', term: 'HRV', fullName: 'Variabilidade da frequência cardíaca', unit: 'ms', category: 'Recuperação', summary: 'Variação do intervalo entre batimentos. Ajuda a observar como o organismo está respondendo ao estresse.', appUse: 'É cruzada com sono, FC de repouso, carga e sensações.', direction: 'Uma queda persistente pode acompanhar recuperação incompleta; maior não é sempre melhor.', baseline: personalBaseline, source: 'Polar', limitations: sensorLimits, related: ['ans-charge', 'fc-repouso'] },
  { id: 'fc-repouso', term: 'FC de repouso', fullName: 'Frequência cardíaca de repouso', unit: 'bpm', category: 'Recuperação', summary: 'Batimentos por minuto quando o corpo está em repouso.', appUse: 'Ajuda a reconhecer esforço fisiológico acima do habitual.', direction: 'Alta persistente em relação ao seu padrão pode pedir cautela; queda isolada não garante prontidão.', baseline: personalBaseline, source: 'Polar', limitations: sensorLimits, related: ['hrv', 'ans-charge'] },
  { id: 'ans-charge', term: 'ANS Charge', fullName: 'Carga do sistema nervoso autônomo', category: 'Recuperação', summary: 'Resume como coração, respiração e HRV se acomodaram nas primeiras horas do sono.', appUse: 'Compõe a leitura de recuperação noturna.', direction: 'Melhor que seu habitual favorece prontidão; pior por vários dias aumenta a cautela.', baseline: personalBaseline, source: 'Polar', limitations: sensorLimits, related: ['nightly-recharge', 'hrv'] },
  { id: 'nightly-recharge', term: 'Nightly Recharge', fullName: 'Recarga noturna', category: 'Recuperação', summary: 'Visão combinada de sono e recuperação do sistema nervoso autônomo.', appUse: 'Ajuda a contextualizar se a noite apoiou a recuperação.', direction: 'Uma noite ruim isolada não cancela automaticamente um treino-chave.', baseline: personalBaseline, source: 'Polar', limitations: sensorLimits, related: ['ans-charge', 'sono'] },
  { id: 'sono', term: 'Sono', fullName: 'Duração e qualidade do sono', unit: 'h e pontuação', category: 'Recuperação', summary: 'Tempo dormido e sinais de continuidade e qualidade da noite.', appUse: 'É comparado com sua duração e regularidade habituais.', direction: 'Quedas persistentes ou combinadas com outros sinais pesam mais que uma noite isolada.', baseline: personalBaseline, source: 'Polar', limitations: 'O relógio estima o sono e pode confundir períodos muito quietos ou interrompidos.', related: ['interrupcoes', 'regularidade'] },
  { id: 'interrupcoes', term: 'Interrupções', fullName: 'Interrupções do sono', category: 'Recuperação', summary: 'Períodos acordado ou com sono fragmentado durante a noite.', appUse: 'Ajuda a interpretar por que muitas horas na cama podem não recuperar bem.', direction: 'Mais interrupções que o habitual podem reduzir a qualidade da recuperação.', baseline: personalBaseline, source: 'Polar', limitations: 'Movimento e leitura do sensor podem alterar a estimativa.', related: ['sono'] },
  { id: 'regularidade', term: 'Regularidade', fullName: 'Regularidade do sono', category: 'Recuperação', summary: 'Consistência dos horários e da duração do sono.', appUse: 'Dá contexto à tendência, evitando julgar uma noite sozinha.', direction: 'Maior consistência costuma facilitar recuperação, mas não substitui duração e qualidade.', baseline: personalBaseline, source: 'Polar', limitations: 'Mudanças de rotina, viagem e turnos precisam ser consideradas.', related: ['sono'] },
  { id: 'ctl', term: 'Fitness / CTL', fullName: 'Carga crônica de treinamento', unit: 'pontos de carga', category: 'Carga', summary: 'Média suavizada da carga das últimas semanas; representa o trabalho que você vem sustentando.', appUse: 'Ajuda a entender sua base atual e evitar estagnação ou progressão brusca.', direction: 'Subir gradualmente indica mais carga sustentada; maior não significa automaticamente melhor forma.', baseline: personalBaseline, source: 'Intervals.icu', limitations: 'Depende da qualidade das zonas, potência, FC e carga registradas.', related: ['atl', 'forma', 'rampa'] },
  { id: 'atl', term: 'Fadiga / ATL', fullName: 'Carga aguda de treinamento', unit: 'pontos de carga', category: 'Carga', summary: 'Média recente que reage rapidamente aos treinos dos últimos dias.', appUse: 'Ajuda a estimar o cansaço acumulado de curto prazo.', direction: 'Sobe após blocos exigentes e cai com recuperação; nem toda alta é ruim.', baseline: personalBaseline, source: 'Intervals.icu', limitations: 'Não mede sozinho dor, doença, sono ou estresse fora do treino.', related: ['ctl', 'forma'] },
  { id: 'forma', term: 'Forma', fullName: 'Balanço entre carga crônica e fadiga', unit: 'pontos', category: 'Carga', summary: 'Mostra a diferença entre o trabalho sustentado e a fadiga recente.', appUse: 'É combinada com recuperação para avaliar a margem do treino do dia.', direction: 'Muito negativa pode indicar fadiga; muito positiva pode refletir descanso ou perda de carga.', baseline: personalBaseline, source: 'Intervals.icu', limitations: 'Não é uma nota universal de desempenho e depende das cargas anteriores.', related: ['ctl', 'atl'] },
  { id: 'rampa', term: 'Rampa', fullName: 'Taxa de mudança da carga crônica', unit: 'pontos por período', category: 'Carga', summary: 'Velocidade com que a carga sustentada está aumentando ou diminuindo.', appUse: 'Ajuda a evitar saltos de carga incompatíveis com sua recuperação.', direction: 'Subida controlada pode apoiar evolução; subida rápida exige maior observação.', baseline: personalBaseline, source: 'Intervals.icu', limitations: 'Não existe uma faixa perfeita igual para todos.', related: ['ctl', 'carga-acumulada'] },
  { id: 'carga-cardiovascular', term: 'Carga cardiovascular', fullName: 'Carga baseada na resposta do coração', category: 'Carga', summary: 'Estima quanto o sistema cardiovascular foi exigido.', appUse: 'Complementa potência e percepção quando disponível.', direction: 'Alta pode ser esperada em treino duro; repetição sem recuperação merece cautela.', baseline: personalBaseline, source: 'Polar', limitations: 'Calor, desidratação, estresse e zonas de FC influenciam a medida.', related: ['fc-repouso', 'carga-treino'] },
  { id: 'carga-treino', term: 'Carga do treino', fullName: 'Carga estimada da sessão', unit: 'pontos', category: 'Carga', summary: 'Resume duração e intensidade em uma medida comparável.', appUse: 'Compara o planejado, o realizado e o impacto na semana.', direction: 'Mais carga significa mais estímulo e também mais recuperação necessária.', baseline: personalBaseline, source: 'Intervals.icu', limitations: 'Sessões diferentes podem gerar a mesma carga com efeitos distintos.', related: ['carga-acumulada', 'intensidade'] },
  { id: 'carga-acumulada', term: 'Carga acumulada', fullName: 'Soma de carga no período', unit: 'pontos', category: 'Carga', summary: 'Total de carga reunido em dias ou semanas.', appUse: 'Ajuda a entender se um treino extra compromete o restante do plano.', direction: 'Deve acompanhar o objetivo e a capacidade de recuperar, não apenas crescer.', baseline: personalBaseline, source: 'Intervals.icu', limitations: 'Não representa sozinho a distribuição nem a especificidade dos estímulos.', related: ['carga-treino', 'rampa'] },
  { id: 'potencia-media', term: 'Potência média', fullName: 'Potência média', unit: 'W', category: 'Treino', summary: 'Média da força produzida nos pedais durante a sessão.', appUse: 'Ajuda a comparar sessões semelhantes.', direction: 'Maior potência no mesmo esforço pode indicar melhora, quando o contexto é comparável.', baseline: personalBaseline, source: 'Intervals.icu', limitations: 'Terreno, pausas, vento, equipamento e tipo de treino mudam a leitura.', related: ['potencia-ponderada', 'eficiencia'] },
  { id: 'potencia-ponderada', term: 'Potência ponderada', fullName: 'Potência normalizada ou ponderada', unit: 'W', category: 'Treino', summary: 'Estimativa que dá mais peso às variações intensas que a média simples.', appUse: 'Ajuda a representar o custo de sessões irregulares ou intervaladas.', direction: 'Distância maior da potência média sugere esforço mais variável.', baseline: personalBaseline, source: 'Intervals.icu', limitations: 'É um modelo e depende de potência confiável e duração suficiente.', related: ['potencia-media', 'intensidade'] },
  { id: 'intensidade', term: 'Intensidade', fullName: 'Intensidade relativa', unit: '% da referência', category: 'Treino', summary: 'Quão exigente foi o esforço em relação às suas capacidades configuradas.', appUse: 'Define o estímulo e qual variável pode ser reduzida em uma adaptação.', direction: 'Mais intensidade não é sempre melhor; precisa caber no objetivo e na recuperação.', baseline: personalBaseline, source: 'Intervals.icu', limitations: 'FTP e zonas desatualizados distorcem a interpretação.', related: ['ftp', 'densidade'] },
  { id: 'cadencia', term: 'Cadência', fullName: 'Cadência de pedalada', unit: 'rpm', category: 'Treino', summary: 'Número de voltas do pedal por minuto.', appUse: 'Ajuda a reconhecer execução técnica e comparar sessões.', direction: 'Não há um número universal ideal; terreno, objetivo e conforto importam.', baseline: personalBaseline, source: 'Intervals.icu', limitations: 'Sensor ausente ou falhas de leitura podem criar lacunas.', related: ['potencia-media'] },
  { id: 'rpe', term: 'RPE', fullName: 'Percepção subjetiva de esforço', unit: 'escala pessoal', category: 'Treino', summary: 'Sua avaliação de quão difícil o treino pareceu.', appUse: 'Confere se potência, coração e sensação contam a mesma história.', direction: 'RPE maior com desempenho igual pode acompanhar fadiga, calor ou estresse.', baseline: personalBaseline, source: 'Percepção do atleta', limitations: 'É subjetivo, mas valioso quando registrado com consistência.', related: ['eficiencia', 'desacoplamento'] },
  { id: 'eficiencia', term: 'Eficiência potência–coração', fullName: 'Relação entre potência e frequência cardíaca', category: 'Treino', summary: 'Observa quanta potência você produz para determinado esforço cardíaco.', appUse: 'Compara evolução em sessões pessoais semelhantes.', direction: 'Melhora persistente pode indicar adaptação; um dia isolado pode refletir condições externas.', baseline: personalBaseline, source: 'Cálculo do app', limitations: 'Calor, cafeína, hidratação, fadiga e sensores afetam a relação.', related: ['potencia-media', 'fc-repouso', 'desacoplamento'] },
  { id: 'desacoplamento', term: 'Desacoplamento', fullName: 'Desacoplamento aeróbico ou cardíaco', unit: '%', category: 'Treino', summary: 'Mostra se o coração precisou trabalhar progressivamente mais para sustentar potência semelhante.', appUse: 'Ajuda a avaliar resistência e estabilidade em treinos contínuos.', direction: 'Menor costuma indicar melhor estabilidade, mas tipo de treino e condições precisam ser comparáveis.', baseline: personalBaseline, source: 'Intervals.icu', limitations: 'Intervalos, subidas, calor, hidratação e pausas podem invalidar a comparação.', related: ['eficiencia', 'endurance'] },
  { id: 'ftp', term: 'FTP', fullName: 'Potência funcional de limiar', unit: 'W', category: 'Planejamento', summary: 'Referência de potência sustentável usada para definir zonas e intensidade.', appUse: 'Orienta a estrutura dos treinos e a leitura de carga.', direction: 'Deve ser atualizada com evidência consistente; um recorde curto não define nova FTP.', baseline: personalBaseline, source: 'Intervals.icu', limitations: 'Protocolos e estado do dia influenciam a estimativa.', related: ['intensidade', 'especificidade'] },
  { id: 'prontidao', term: 'Prontidão', fullName: 'Prontidão verde, amarela ou vermelha', category: 'Planejamento', summary: 'Síntese diária de recuperação, carga, tendência e percepção.', appUse: 'Verde mantém; amarela propõe ajuste moderado; vermelha propõe recuperação ou descanso.', direction: 'É uma decisão contextual, não uma nota fixa de saúde.', baseline: personalBaseline, source: 'Cálculo do app', limitations: 'Dados ausentes ou contraditórios suspendem mudanças; não substitui avaliação profissional.', related: ['treino-chave', 'recuperacao-ativa'] },
  { id: 'treino-chave', term: 'Treino-chave', fullName: 'Sessão prioritária do ciclo', category: 'Planejamento', summary: 'Treino que entrega um estímulo importante para a fase e o objetivo atual.', appUse: 'É preservado quando possível e não é cancelado por uma noite ruim isolada.', direction: 'Sua prioridade depende do ciclo, não apenas da dificuldade.', baseline: personalBaseline, source: 'Cálculo do app', limitations: 'Calendário e objetivo precisam estar atualizados.', related: ['especificidade', 'prontidao'] },
  { id: 'especificidade', term: 'Especificidade', fullName: 'Semelhança do estímulo com o objetivo', category: 'Planejamento', summary: 'Quanto o treino prepara exatamente a capacidade exigida pela meta.', appUse: 'Ganha proteção especial perto de uma meta principal.', direction: 'Mais específica é útil perto da meta; base geral continua importante em outras fases.', baseline: personalBaseline, source: 'Cálculo do app', limitations: 'Depende de objetivo, data e prioridade corretamente informados.', related: ['treino-chave', 'volume'] },
  { id: 'volume', term: 'Volume', fullName: 'Quantidade total de treino', unit: 'tempo ou distância', category: 'Planejamento', summary: 'Quanto trabalho é realizado, sem dizer sozinho quão intenso ele foi.', appUse: 'Pode ser reduzido preservando a qualidade principal do treino.', direction: 'Mais volume exige adaptação gradual e recuperação compatível.', baseline: personalBaseline, source: 'Intervals.icu', limitations: 'Tempo e distância têm significados diferentes conforme terreno e intensidade.', related: ['intensidade', 'densidade'] },
  { id: 'densidade', term: 'Densidade', fullName: 'Relação entre esforço e recuperação', category: 'Planejamento', summary: 'Quanto trabalho intenso cabe em determinado tempo e quanto descanso existe entre blocos.', appUse: 'Evita mudar volume, intensidade e densidade ao mesmo tempo.', direction: 'Maior densidade torna a sessão mais exigente mesmo com duração igual.', baseline: personalBaseline, source: 'Cálculo do app', limitations: 'Precisa da estrutura completa do treino para ser interpretada.', related: ['volume', 'intensidade'] },
  { id: 'endurance', term: 'Endurance', fullName: 'Resistência aeróbica leve a moderada', category: 'Planejamento', summary: 'Treino sustentável que desenvolve capacidade de pedalar por mais tempo.', appUse: 'Pode substituir intensidade quando a recuperação está limitada.', direction: 'Consistência importa mais que transformar toda sessão em treino longo.', baseline: personalBaseline, source: 'Cálculo do app', limitations: 'Zonas incorretas podem tornar o treino mais intenso que o planejado.', related: ['recuperacao-ativa', 'desacoplamento'] },
  { id: 'recuperacao-ativa', term: 'Recuperação ativa', fullName: 'Movimento muito leve para recuperação', category: 'Planejamento', summary: 'Sessão curta e fácil, sem objetivo de acumular carga relevante.', appUse: 'É uma opção conservadora quando descanso total não é necessário.', direction: 'Deve terminar com sensação melhor ou igual à inicial; não é treino escondido.', baseline: personalBaseline, source: 'Cálculo do app', limitations: 'Dor, sintomas ou piora podem indicar que descanso é mais apropriado.', related: ['prontidao', 'endurance'] },
];

export function glossaryById(id: string) {
  return glossary.find((entry) => entry.id === id);
}
